In [1]:
# Data Loading and Numerical Operations
import pandas as pd
import numpy as np
import time
# Data Visualizations
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
# Data Resampling
from sklearn.utils import resample
# Data Feature Selection
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
# Data Splitting
from sklearn.model_selection import train_test_split
# Data Scaling
from sklearn.preprocessing import MinMaxScaler
# Data Modeling
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, roc_curve, classification_report
# Hyperparameter Tuning
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
# Ensembling
from mlxtend.classifier import StackingCVClassifier

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.utils import resample
import numpy as np
from sklearn.feature_selection import SelectKBest
df = pd.read_csv('heart.csv')
X=df.iloc[:,1:22]
y=df.iloc[:,0]
print("X - ", X.shape, "\ny - ", y.shape)



target1=df[df['HeartDiseaseorAttack']==1]
target0=df[df['HeartDiseaseorAttack']==0]
     
target1=resample(target1,replace=True,n_samples=len(target0),random_state=40)
     
target=pd.concat([target0,target1])
     
df=target
print(np.shape(df))



y = df['HeartDiseaseorAttack']
X = df.drop(['HeartDiseaseorAttack'], axis=1)


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X -  (253680, 21) 
y -  (253680,)
(459574, 22)


### LR

In [3]:
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report



# Initialize the logistic regression model
model = LogisticRegression()
start_time = time.time()
# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
end_time = time.time() - start_time
# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

# Classification Report
classification_rep = classification_report(y_test, y_pred)
print("\nClassification Report:\n", classification_rep)

# ROC AUC
roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print("\nROC AUC Score:", roc_auc)

# Specificity, Sensitivity, NPV, PPV
tn, fp, fn, tp = conf_matrix.ravel()
specificity = tn / (tn + fp)
sensitivity = tp / (tp + fn)
npv = tn / (tn + fn)
ppv = tp / (tp + fp)

print("\nSpecificity:", specificity)
print("Sensitivity:", sensitivity)
print("NPV:", npv)
print("PPV:", ppv)
print("Time Taken:", end_time)

C:\Users\Hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.7641516618615025

Confusion Matrix:
 [[33910 11978]
 [ 9700 36327]]

Classification Report:
               precision    recall  f1-score   support

         0.0       0.78      0.74      0.76     45888
         1.0       0.75      0.79      0.77     46027

    accuracy                           0.76     91915
   macro avg       0.76      0.76      0.76     91915
weighted avg       0.76      0.76      0.76     91915


ROC AUC Score: 0.8420213600142952

Specificity: 0.7389731520223152
Sensitivity: 0.7892541334434137
NPV: 0.7775739509286861
PPV: 0.7520339509367561
Time Taken: 3.5067169666290283


### MLP

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report



# Initialize the MLP classifier with sigmoid activation
model = MLPClassifier(hidden_layer_sizes=(50,), activation='logistic', max_iter=500, random_state=42)

# Train the model on the training data
start_time = time.time()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
end_time = time.time() - start_time
# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

# Classification Report
classification_rep = classification_report(y_test, y_pred)
print("\nClassification Report:\n", classification_rep)

# ROC AUC
roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print("\nROC AUC Score:", roc_auc)

tn, fp, fn, tp = conf_matrix.ravel()
specificity = tn / (tn + fp)
sensitivity = tp / (tp + fn)
npv = tn / (tn + fn)
ppv = tp / (tp + fp)

print("\nSpecificity:", specificity)
print("Sensitivity:", sensitivity)
print("NPV:", npv)
print("PPV:", ppv)
print("Time Taken:", end_time)

Accuracy: 0.7787085894576511

Confusion Matrix:
 [[33876 12012]
 [ 8328 37699]]

Classification Report:
               precision    recall  f1-score   support

         0.0       0.80      0.74      0.77     45888
         1.0       0.76      0.82      0.79     46027

    accuracy                           0.78     91915
   macro avg       0.78      0.78      0.78     91915
weighted avg       0.78      0.78      0.78     91915


ROC AUC Score: 0.8561490324724202

Specificity: 0.7382322175732218
Sensitivity: 0.8190627240532731
NPV: 0.8026727324424225
PPV: 0.7583633401058116
Time Taken: 214.0006206035614


### CAT

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report



# Initialize the CatBoost classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.1, loss_function='Logloss', random_state=42)

# Train the model on the training data
start_time = time.time()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
end_time = time.time() - start_time
# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

# Classification Report
classification_rep = classification_report(y_test, y_pred)
print("\nClassification Report:\n", classification_rep)

# ROC AUC
roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print("\nROC AUC Score:", roc_auc)

tn, fp, fn, tp = conf_matrix.ravel()
specificity = tn / (tn + fp)
sensitivity = tp / (tp + fn)
npv = tn / (tn + fn)
ppv = tp / (tp + fp)

print("\nSpecificity:", specificity)
print("Sensitivity:", sensitivity)
print("NPV:", npv)
print("PPV:", ppv)
print("Time Taken:", end_time)

0:	learn: 0.6466163	total: 365ms	remaining: 3m 2s
1:	learn: 0.6100689	total: 562ms	remaining: 2m 19s
2:	learn: 0.5814534	total: 727ms	remaining: 2m
3:	learn: 0.5597481	total: 962ms	remaining: 1m 59s
4:	learn: 0.5422159	total: 1.16s	remaining: 1m 54s
5:	learn: 0.5284208	total: 1.33s	remaining: 1m 49s
6:	learn: 0.5174573	total: 1.48s	remaining: 1m 44s
7:	learn: 0.5083680	total: 1.67s	remaining: 1m 42s
8:	learn: 0.5015188	total: 1.93s	remaining: 1m 45s
9:	learn: 0.4956482	total: 2.1s	remaining: 1m 43s
10:	learn: 0.4907387	total: 2.28s	remaining: 1m 41s
11:	learn: 0.4866678	total: 2.47s	remaining: 1m 40s
12:	learn: 0.4832423	total: 2.67s	remaining: 1m 39s
13:	learn: 0.4804283	total: 2.87s	remaining: 1m 39s
14:	learn: 0.4776433	total: 3.08s	remaining: 1m 39s
15:	learn: 0.4754878	total: 3.28s	remaining: 1m 39s
16:	learn: 0.4734049	total: 3.46s	remaining: 1m 38s
17:	learn: 0.4714238	total: 3.63s	remaining: 1m 37s
18:	learn: 0.4697312	total: 3.8s	remaining: 1m 36s
19:	learn: 0.4683946	total: 4

160:	learn: 0.3901832	total: 21.2s	remaining: 44.6s
161:	learn: 0.3897807	total: 21.3s	remaining: 44.5s
162:	learn: 0.3894653	total: 21.4s	remaining: 44.3s
163:	learn: 0.3890737	total: 21.5s	remaining: 44.1s
164:	learn: 0.3887207	total: 21.7s	remaining: 44s
165:	learn: 0.3882462	total: 21.8s	remaining: 43.8s
166:	learn: 0.3878712	total: 21.9s	remaining: 43.7s
167:	learn: 0.3874894	total: 22s	remaining: 43.5s
168:	learn: 0.3871231	total: 22.1s	remaining: 43.4s
169:	learn: 0.3866409	total: 22.3s	remaining: 43.2s
170:	learn: 0.3862619	total: 22.4s	remaining: 43s
171:	learn: 0.3858903	total: 22.5s	remaining: 42.9s
172:	learn: 0.3855102	total: 22.6s	remaining: 42.7s
173:	learn: 0.3851871	total: 22.7s	remaining: 42.6s
174:	learn: 0.3846993	total: 22.9s	remaining: 42.4s
175:	learn: 0.3843603	total: 23s	remaining: 42.3s
176:	learn: 0.3842469	total: 23.1s	remaining: 42.2s
177:	learn: 0.3837833	total: 23.2s	remaining: 42s
178:	learn: 0.3834387	total: 23.4s	remaining: 41.9s
179:	learn: 0.3829620	

320:	learn: 0.3389559	total: 41.5s	remaining: 23.1s
321:	learn: 0.3387290	total: 41.6s	remaining: 23s
322:	learn: 0.3383998	total: 41.7s	remaining: 22.9s
323:	learn: 0.3382786	total: 41.9s	remaining: 22.7s
324:	learn: 0.3380578	total: 42s	remaining: 22.6s
325:	learn: 0.3377526	total: 42.1s	remaining: 22.5s
326:	learn: 0.3375726	total: 42.2s	remaining: 22.3s
327:	learn: 0.3373233	total: 42.3s	remaining: 22.2s
328:	learn: 0.3371502	total: 42.5s	remaining: 22.1s
329:	learn: 0.3369138	total: 42.6s	remaining: 21.9s
330:	learn: 0.3366930	total: 42.7s	remaining: 21.8s
331:	learn: 0.3364523	total: 42.8s	remaining: 21.7s
332:	learn: 0.3362519	total: 43s	remaining: 21.6s
333:	learn: 0.3360741	total: 43.1s	remaining: 21.4s
334:	learn: 0.3357937	total: 43.2s	remaining: 21.3s
335:	learn: 0.3356542	total: 43.4s	remaining: 21.2s
336:	learn: 0.3354125	total: 43.5s	remaining: 21s
337:	learn: 0.3350796	total: 43.6s	remaining: 20.9s
338:	learn: 0.3348415	total: 43.7s	remaining: 20.8s
339:	learn: 0.334457

480:	learn: 0.3041204	total: 1m 1s	remaining: 2.45s
481:	learn: 0.3040486	total: 1m 2s	remaining: 2.32s
482:	learn: 0.3037834	total: 1m 2s	remaining: 2.19s
483:	learn: 0.3036242	total: 1m 2s	remaining: 2.06s
484:	learn: 0.3033626	total: 1m 2s	remaining: 1.93s
485:	learn: 0.3032445	total: 1m 2s	remaining: 1.8s
486:	learn: 0.3030282	total: 1m 2s	remaining: 1.67s
487:	learn: 0.3027984	total: 1m 2s	remaining: 1.54s
488:	learn: 0.3024912	total: 1m 2s	remaining: 1.42s
489:	learn: 0.3021746	total: 1m 3s	remaining: 1.29s
490:	learn: 0.3020575	total: 1m 3s	remaining: 1.16s
491:	learn: 0.3018553	total: 1m 3s	remaining: 1.03s
492:	learn: 0.3017295	total: 1m 3s	remaining: 901ms
493:	learn: 0.3015611	total: 1m 3s	remaining: 772ms
494:	learn: 0.3014144	total: 1m 3s	remaining: 644ms
495:	learn: 0.3012737	total: 1m 3s	remaining: 515ms
496:	learn: 0.3010632	total: 1m 3s	remaining: 386ms
497:	learn: 0.3008720	total: 1m 4s	remaining: 257ms
498:	learn: 0.3006640	total: 1m 4s	remaining: 129ms
499:	learn: 0

### ADA

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report



# Initialize the AdaBoost classifier with a base estimator (e.g., DecisionTreeClassifier)
base_estimator = None  # You can use another classifier as the base estimator
model = AdaBoostClassifier(base_estimator=base_estimator, n_estimators=50, random_state=42)

# Train the model on the training data
start_time = time.time()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
end_time = time.time() - start_time
# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

# Classification Report
classification_rep = classification_report(y_test, y_pred)
print("\nClassification Report:\n", classification_rep)

# ROC AUC (Note: AdaBoost doesn't have a `predict_proba` method, so we use decision function for ROC AUC)
roc_auc = roc_auc_score(y_test, model.decision_function(X_test))
print("\nROC AUC Score:", roc_auc)

tn, fp, fn, tp = conf_matrix.ravel()
specificity = tn / (tn + fp)
sensitivity = tp / (tp + fn)
npv = tn / (tn + fn)
ppv = tp / (tp + fp)

print("\nSpecificity:", specificity)
print("Sensitivity:", sensitivity)
print("NPV:", npv)
print("PPV:", ppv)
print("Time Taken:", end_time)

C:\Users\Hp\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


Accuracy: 0.7687646194853941

Confusion Matrix:
 [[34504 11384]
 [ 9870 36157]]

Classification Report:
               precision    recall  f1-score   support

         0.0       0.78      0.75      0.76     45888
         1.0       0.76      0.79      0.77     46027

    accuracy                           0.77     91915
   macro avg       0.77      0.77      0.77     91915
weighted avg       0.77      0.77      0.77     91915


ROC AUC Score: 0.8471629041947182

Specificity: 0.7519177126917713
Sensitivity: 0.7855606491841745
NPV: 0.777572452336954
PPV: 0.7605435308470583
Time Taken: 19.097728729248047


### XG

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report



# Initialize the XGBoost classifier
model = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
start_time = time.time()
# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
end_time = time.time() - start_time
# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

# Classification Report
classification_rep = classification_report(y_test, y_pred)
print("\nClassification Report:\n", classification_rep)

# ROC AUC
roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print("\nROC AUC Score:", roc_auc)

tn, fp, fn, tp = conf_matrix.ravel()
specificity = tn / (tn + fp)
sensitivity = tp / (tp + fn)
npv = tn / (tn + fn)
ppv = tp / (tp + fp)

print("\nSpecificity:", specificity)
print("Sensitivity:", sensitivity)
print("NPV:", npv)
print("PPV:", ppv)
print("Time Taken:", end_time)

Accuracy: 0.7748680846434206

Confusion Matrix:
 [[33482 12406]
 [ 8287 37740]]

Classification Report:
               precision    recall  f1-score   support

         0.0       0.80      0.73      0.76     45888
         1.0       0.75      0.82      0.78     46027

    accuracy                           0.77     91915
   macro avg       0.78      0.77      0.77     91915
weighted avg       0.78      0.77      0.77     91915


ROC AUC Score: 0.8518369702309078

Specificity: 0.7296460948396095
Sensitivity: 0.8199535055510896
NPV: 0.8015992721875075
PPV: 0.7526024009891118
Time Taken: 2.0325756072998047


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt



# Initialize classifiers
classifiers = [
    LogisticRegression(),
    MLPClassifier(hidden_layer_sizes=(50,), activation='logistic', max_iter=500, random_state=42),
    AdaBoostClassifier(n_estimators=50, random_state=42),
    XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42),
    CatBoostClassifier(iterations=500, depth=10, learning_rate=0.1, loss_function='Logloss', random_state=42)
]

# Plot ROC curves for each classifier
plt.figure(figsize=(10, 8))

for clf in classifiers:
    clf.fit(X_train, y_train)
    y_scores = clf.predict_proba(X_test)[:, 1]
    fpr, tpr, _ = roc_curve(y_test, y_scores)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'{clf.__class__.__name__} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Random Guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curves for Different Classifiers')
plt.legend(loc='lower right')
plt.show()
